;------------------------------------------------------------------------
;  dbgutil.inc
;  Copyright (c)2021 Kevin Boone, GPL v3.0
;------------------------------------------------------------------------

; List of the global symbols in intmath 

	.Z80

; mul16 
; Multiply HL by DE, result in HL 
external mul16 

; div16 
; Divide HL by DE, result in HL, remainder in DE
external div16 


